// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwmntpwkxlftajqwwqil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3bW50cHdreGxmdGFqcXd3cWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjQyNzksImV4cCI6MjA2MjA0MDI3OX0.w-YcEv-vLRaafnt0E7jUvJ6_qUg8iSZzkNilfLOZec0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);